config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root to: "pages#home"

  resources :jobs do
    resources :applications, only: [:new, :create, :show, :index]
  end
  resources :events, only: [:index, :new, :create, :show, :destroy] do
    resources :attendees, only: [:index, :create, :new]
  end

  resources :applications, only: [:destroy]
  resources :pages, only: [:index, :show]

  post "/levelup", to: "pages#levelup"
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  belongs_to :employer
  has_many :applications

  validates :title, presence: true
  validates :_type, presence: true
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show ]
  before_action :set_user
  before_action :set_event, only: [:destroy]


  def index
    # @jobs = Job.page(params[:page]).per(7)
    @jobs = Job.all

    @jobs = @jobs.where("title ILIKE :title", title: "%#{params[:title]}%") if params[:title].present?
    @jobs = @jobs.where("city ILIKE :city", city: "%#{params[:city]}%") if params[:city].present?

    if params[:ft] || params[:pt] || params[:fl] || params[:is] || params[:ws]
      @filtered_jobs_type = []
      @filtered_jobs_type << @jobs.where(_type: params[:ft]) if params[:ft]
      @filtered_jobs_type << @jobs.where(_type: params[:pt]) if params[:pt]
      @filtered_jobs_type << @jobs.where(_type: params[:fl]) if params[:fl]
      @filtered_jobs_type << @jobs.where(_type: params[:is]) if params[:is]
      @filtered_jobs_type << @jobs.where(_type: params[:ws]) if params[:ws]
      arr = @filtered_jobs_type.flatten
      @jobs = Job.where(id: arr.map(&:id))
    end

    if params[:skills].present? && params[:skills] != "Choose..."
      @jobs = @jobs.where(category: params[:skills])
    end

    if params[:tn] || params[:sm] || params[:md] || params[:lg] || params[:xl] || params[:xxl]
      @filtered_jobs_company_size = []
      @filtered_jobs_company_size << @jobs.where(companySize: params[:tn]) if params[:tn]
      @filtered_jobs_company_size << @jobs.where(companySize: params[:sm]) if params[:sm]
      @filtered_jobs_company_size << @jobs.where(companySize: params[:md]) if params[:md]
      @filtered_jobs_company_size << @jobs.where(companySize: params[:lg]) if params[:lg]
      @filtered_jobs_company_size << @jobs.where(companySize: params[:xl]) if params[:xl]
      @filtered_jobs_company_size << @jobs.where(companySize: params[:xxl]) if params[:xxl]
      arr = @filtered_jobs_company_size.flatten
      @jobs = Job.where(id: arr.map(&:id))
    end

    if params[:os] || params[:rm] || params[:hy]
      @filtered_jobs_on_site = []
      @filtered_jobs_on_site << @jobs.where(onsite: params[:os]) if params[:os]
      @filtered_jobs_on_site << @jobs.where(onsite: params[:rm]) if params[:rm]
      @filtered_jobs_on_site << @jobs.where(onsite: params[:hy]) if params[:hy]
      arr = @filtered_jobs_on_site.flatten
      @jobs = Job.where(id: arr.map(&:id))
    end

  end

  def show
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    @job.user_id = @job.id
    if @job.save
      redirect_to job_path(@job)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def destroy
    @job.destroy
    redirect_to events_path, status: :see_other
  end

  def job_params
    params.require(:job).permit(:title, :_type)
  end

  def set_user
    @user = current_user
  end

  def set_job
    @job = Job.find(params[:job_id])
  end


end

app/views/jobs/create.html.erb
<h1>Jobs#create</h1>
<p>Find me in app/views/jobs/create.html.erb</p>

app/views/jobs/destroy.html.erb
<h1>Jobs#destroy</h1>
<p>Find me in app/views/jobs/destroy.html.erb</p>

app/views/jobs/edit.html.erb
<h1>Jobs#edit</h1>
<p>Find me in app/views/jobs/edit.html.erb</p>

app/views/jobs/index.html.erb
<%= render "shared/navbar" %>

<div class="bg-main main-padding" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://t4.ftcdn.net/jpg/04/09/70/87/360_F_409708782_HxuxOH8f7xSmj5p4ygbAbuJE74vGGj2N.jpg); min-height: 250vh;">
  <div class="container">
  <h1 class="text-center mb-4">Available Jobs</h1>
    <div id="create-job" class="text-center">
    <%= link_to "Create a New Job", new_job_path, class: "btn btn-secondary2" %>
  </div>
    <div class="row">
      <div class="card-product col-4 text-light d-grid">
        <div>
          <img class="w-100" src="https://thumbs.gfycat.com/DopeyLegitimateGaur-max-1mb.gif" />
        </div>
        <div class="module-border-wrap">
          <div class="col card-product-infos p-2" id="search-text">
            <form action="<%= jobs_path %>" method="GET">
              <fieldset>
              <legend class="play-font fs-4">Results</legend>
                <p class="text-light py-2">Found <strong><%= pluralize(@jobs.size, "job") %>
                </strong></p>
              </fieldset>
              <fieldset>
              <hr>
              <legend class="play-font">Search</legend>
                <div class="form-group d-flex">
                  <p>
                    <label for="title" class="text-light form-input-label form-input justify-content-end">Job Title</label>
                    <input class="module-border-wrap text-placeholder" type="text" id="title" name="title" <%= "value=#{params[:title].capitalize}" if params[:title].present? %> placeholder="Search for title...">
                  </p>
                  <p>
                    <label for="location" class="text-light form-input-label">Location</label>
                    <input class="module-border-wrap text-placeholder form-input bg-white justify-content-end" type="text" id="location" name="city" <%= "value=#{params[:city].capitalize}" if params[:city].present? %> placeholder="Search for city...">
                  </p>
                </div>
              </fieldset>
              <fieldset>
              <hr>
              <legend class="play-font">Job Types</legend>
                <div class="form-check bg-transparent pt-1 pb-3 d-flex">
                  <div class="flex-row">
                    <p>
                      <input type="checkbox" id="fulltime" name="ft" value="Fulltime" <%= "checked" if params[:ft] %> class="form-check-input box-bg">
                      <label for="fulltime" class="text-light form-check-label">Fulltime</label>
                    </p>
                    <p>
                      <input type="checkbox" id="parttime" name="pt" value="Parttime" <%= "checked" if params[:pt] %> class="form-check-input box-bg">
                      <label for="parttime" class="text-light form-check-label">Parttime</label>
                    </p>
                    <p>
                      <input type="checkbox" id="freelancer" name="fl" value="Freelancer" <%= "checked" if params[:fl] %> class="form-check-input box-bg">
                      <label for="freelancer" class="text-light form-check-label">Freelancer</label>
                    </p>
                  </div>

                  <div class="flex-row ms-5">
                    <p>
                      <input type="checkbox" id="internship" name="is" value="Internship" <%= "checked" if params[:is] %> class="form-check-input box-bg">
                      <label for="internship" class="text-light form-check-label">Internship</label>
                    </p>
                    <p>
                      <input type="checkbox" id="working-student" name="ws" value="Working Student" <%= "checked" if params[:ws] %> class="form-check-input box-bg">
                      <label for="working-student" class="text-light form-check-label">Working Student</label>
                    </p>
                  </div>

                </div>
              </fieldset>
              <hr>
              <fieldset>
                <legend class="play-font">Job Category</legend>
                <div class="form-select module-border-wrap category-border">
                  <select id="skills" name="skills" class="form-control">
                    <option selected>Choose...</option>
                    <option>Sound</option>
                    <option>Artist</option>
                    <option>Developer</option>
                    <option>Engineer</option>
                    <option>Sales</option>
                  </select>
                </div>
              </fieldset>
              <hr>
              <legend class="play-font">Company Size</legend>
                <div class="form-check bg-transparent dark pt-1 pb-3">
                  <div>
                    <div class="d-inline-block">
                    <p>
                      <input type="checkbox" id="tiny" name="tn" value="1-10" <%= "checked" if params[:tn] %> class="form-check-input box-bg">
                      <label for="tiny" class="text-light form-check-label">1 - 10</label>
                    </p>
                    </div>
                    <div class="d-inline-block ms-5">
                      <p>
                        <input type="checkbox" id="small" name="sm" value="11-50" <%= "checked" if params[:sm] %> class="form-check-input box-bg">
                        <label for="small" class="text-light form-check-label">11 - 50</label>
                      </p>
                    </div>
                    <div class="d-inline-block ms-5">
                      <p>
                        <input type="checkbox" id="medium" name="md" value="51-200" <%= "checked" if params[:md] %> class="form-check-input box-bg">
                        <label for="medium" class="text-light form-check-label">51 - 200</label>
                      </p>
                    </div>
                  </div>
                  <div>
                    <div class="d-inline-block">
                    <p>
                      <input type="checkbox" id="large" name="lg" value="201-500" <%= "checked" if params[:lg] %> class="form-check-input box-bg">
                      <label for="large" class="text-light form-check-label">201 - 500</label>
                    </p>
                    </div>
                    <div class="d-inline-block ms-5">
                      <p>
                        <input type="checkbox" id="x-large" name="xl" value="501-1000" <%= "checked" if params[:xl] %> class="form-check-input box-bg">
                        <label for="x-large" class="text-light form-check-label">501 - 1000</label>
                      </p>
                    </div>
                    <div class="d-inline-block ms-5">
                      <p>
                        <input type="checkbox" id="xx-large" name="xxl" value="1000+" <%= "checked" if params[:xxl] %> class="form-check-input box-bg">
                        <label for="xx-large" class="text-light form-check-label">1000+</label>
                      </p>
                    </div>
                  </div>
                </div>
              </fieldset>
              <hr>
              <legend class="play-font">On-site</legend>
                <div class="form-check bg-transparent pt-1 pb-3">
                  <div class="d-inline-block">
                    <p>
                      <input type="checkbox" id="on-site" name="os" value="On-site" <%= "checked" if params[:os] %> class="form-check-input box-bg">
                      <label for="os" class="text-light form-check-label">On-site</label>
                    </p>
                  </div>
                  <div class="d-inline-block ms-5">
                    <p>
                      <input type="checkbox" id="remote" name="rm" value="Remote" <%= "checked" if params[:rm] %> class="form-check-input box-bg">
                      <label for="remote" class="text-light form-check-label">Remote</label>
                    </p>
                  </div>
                  <div class="d-inline-block ms-5">
                    <p>
                      <input type="checkbox" id="hybrid" name="hy" value="Hybrid" <%= "checked" if params[:hy] %> class="form-check-input box-bg">
                      <label for="hybrid" class="text-light form-check-label">Hybrid</label>
                    </p>
                  </div>

                </div>
              </fieldset>
              <hr>
              <fieldset>
                <div class="d-flex justify-content-center">
                  <button type="Submit" class="btn btn-secondary1 px-5 text-light">Filter</button>
                </div>
              </fieldset>
            </form>
          </div>
        </div>
      </div>


      <div class="col-8">
      <% @jobs.each do |job| %>
        <div class="box">
          <span></span>
          <div class="content">
            <div class="pb-4">
              <%= cl_image_tag job.employer.image.key, height: "40px" %>
            </div>
            <h5> <%= job.title %> at <%= job.employer.companyName  %> </h5>
            <hr>
            <div id="show-more-text">
              <p> <%= job.desc %> </p>
            </div>
            <br>
            <div class="d-flex justify-content-between">
              <div class="fw-bold">
                <%= job._type  %>: €<%=job.salary%>/year
                <img src="https://mario.wiki.gallery/images/9/91/PN_Spinning_Coin.gif" width="20px" />
                <br>
                <%= job.city  %> - Start Date: <%=job.startDate.strftime("%m/%Y")%>
              </div>
              </p>
              <%= link_to "I'm interested", job_path(job), class:"btn col-3 btn-secondary1 fw-bold text-light p-2" %>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/jobs/new.html.erb
<%= render "shared/navbar" %>

<div class="bg-main" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://t4.ftcdn.net/jpg/04/09/70/87/360_F_409708782_HxuxOH8f7xSmj5p4ygbAbuJE74vGGj2N.jpg); padding-top:150px; min-height: 100vh;">
<div class="container" data-controller="coin-sound">
  <div class="detail-card">
    <div class="box box-show" id="box-application">
      <span></span>
      <div class="box-detail">
        <div>
          <h1 class="text-center" style="line-height: 2.5"> <strong> POST A NEW JOB <br /></strong></h1>
            <h5 style="font-size:"><%= simple_form_for [@job] do |job| %>
              <%= job.input :title %>
              <%= job.input :_type %>
              <%= job.input :city %>
              <%= job.input :salary %>
              <%= job.input :category %>
              <%= job.input :desc %>
              <%= job.input :employer_id %>
              <%= job.submit "Submit", class: "btn col-3 btn-secondary1", style:"text-decoration:none; color:#f9fafc; font-weight:bold;" %>
            <% end %>
        </div>

        <div>
          <%= link_to "Back to all Jobs", jobs_path, class: "btn col-3 btn-secondary2", style:"text-shadow: 1px 1px #D217D9; text-decoration:none; color:#f9fafc; font-weight:bold;" %></h5>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/jobs/show.html.erb
<%= render "shared/navbar" %>

<div class="bg-main main-padding" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://t4.ftcdn.net/jpg/04/09/70/87/360_F_409708782_HxuxOH8f7xSmj5p4ygbAbuJE74vGGj2N.jpg);">
<div class="container">
  <div class="detail-card">
    <div class="box box-show">
      <span></span>
      <div class="box-detail">
        <div class="pb-4">
          <%= cl_image_tag @job.employer.image.key, height: "40px" %>
        </div>
        <h3><%= @job.title %> at <%= @job.employer.companyName  %></h3><br>

        <h4>Company Location</h4>
        <%= @job.employer.companyName %>
        <br>
        <%= @job.employer.street %>
        <br>
        <%= @job.employer.postcode %> <%= @job.employer.city %>
        <br><br>
        <h4>Start Date: <%= @job.startDate.strftime("%m/%Y")%></h4>
        <br>
        <h4>Job Description</h4>

        <%= @job.desc  %> <br> <br>

        <p>We thank you for your interest, however, only those candidates selected for an interview will be contacted. <strong>No agencies please.</strong></p>
        <br><br>
        <%= link_to "Apply", new_job_application_path(params[:id]), class:"btn col-3 btn-secondary1 text-light fw-bold" %>

      </div>
    </div>
  </div>
</div>