config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root to: "pages#home"

  resources :jobs do
    resources :applications, only: [:new, :create, :show, :index]
  end
  resources :events, only: [:index, :new, :create, :show, :destroy] do
    resources :attendees, only: [:index, :create, :new]
  end

  resources :applications, only: [:destroy]
  resources :pages, only: [:index, :show]

  post "/levelup", to: "pages#levelup"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">

  <div class="container">
    <div class="d-flex justify-content-center">
      <div class="flex-row">
        <img src="https://i.gifer.com/origin/0a/0a0fa730e0843b2b144cfa57276ae9e3.gif" width="100px" />
      </div>
      <div class="flex-row footer-links">
        <a href="#"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
      </div>
    </div>
    <div class="footer-copyright mt-2">
      © 2022 Nerdadvisor <i class="fa fa-gamepad" aria-hidden="true"></i> All Rights Reserved.
    </div>
  </div>
</div>

app/views/shared/_main-navbar.erb
<div class="navbar navbar-expand-sm navbar-light main-navbar" data-controller="navbar" data-action="scroll@window->navbar#updateNavbar">
  <div class="container-fluid" id="nav-homepage">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>

    <button class="navbar-toggler navbar-dark" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link", data: {turbo: false} %>
          </li>
          <li class="nav-item">
            <%= link_to "Search Jobs", jobs_path, class: "nav-link", data: {turbo: false} %>
          </li>
          <li class="nav-item">
            <%= link_to "Events", events_path, class: "nav-link" %>
          </li>
          <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= image_tag current_user.image, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Dashboard", pages_path, class: "dropdown-item", data: {turbo: false} %>
              <%= link_to "Jobs", jobs_path, class: "dropdown-item", data: {turbo: false} %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item", data: {turbo: false} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item" id="login">
            <%= link_to "Login", new_user_session_path, class: "nav-link", data: {turbo: false} %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" data-controller="navbar" data-action="scroll@window->navbar#updateNavbar">
  <div class="container-fluid" id="nav-homepage">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>

    <button class="navbar-toggler navbar-dark" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link", data: {turbo: false} %>
          </li>
          <li class="nav-item">
            <%= link_to "Search Jobs", jobs_path, class: "nav-link", data: {turbo: false} %>
          </li>
          <li class="nav-item">
            <%= link_to "Events", events_path, class: "nav-link" %>
          </li>
          <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= image_tag current_user.image, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Dashboard", pages_path, class: "dropdown-item", data: {turbo: false} %>
              <%= link_to "Jobs", jobs_path, class: "dropdown-item", data: {turbo: false} %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item" id="login">
            <%= link_to "Login", new_user_session_path, class: "nav-link", data: {turbo: false} %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  </div>
</div>