config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root to: "pages#home"

  resources :jobs do
    resources :applications, only: [:new, :create, :show, :index]
  end
  resources :events, only: [:index, :new, :create, :show, :destroy] do
    resources :attendees, only: [:index, :create, :new]
  end

  resources :applications, only: [:destroy]
  resources :pages, only: [:index, :show]

  post "/levelup", to: "pages#levelup"
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :attendees
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_user
  before_action :set_event, only: [:destroy]

  def index
    @events = Event.all
    @markers = @events.geocoded.map do |event|
      {
        lat: event.latitude,
        lng: event.longitude,
        info_window: render_to_string(partial: "info_window", locals: { event: event }),
        image_url: helpers.asset_url("marker.png")
      }
    end
  end

  def show
    @event = Event.find(params[:id])
    @event.user_id = current_user.id
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user_id = @user.id
    if @event.save
      redirect_to event_path(@event)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path, status: :see_other
  end

  private

  def event_params
    params.require(:event).permit(:title, :date, :desc, :venue, :address, :user_id)
  end

  def set_user
    @user = current_user
  end

  def set_event
    @event = Event.find(params[:event_id])
  end

end

app/views/events/_info_window.html.erb
<h4><%= event.title %></h4>

app/views/events/index.html.erb
<%= render "shared/navbar" %>

<div class="bg-main main-padding" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://t4.ftcdn.net/jpg/04/09/70/87/360_F_409708782_HxuxOH8f7xSmj5p4ygbAbuJE74vGGj2N.jpg); min-height: 80vh;">
  <h1 class="top-pad text-center mb-5">Find exciting gaming events near you!</h1>
  <div id="create-event" class="text-center">
    <%= link_to "Create New Event", new_event_path, class: "btn btn-secondary2" %>
  </div>

  <div class="container d-flex" style="min-height:1000px;">
    <div class="container flex-row" id="show-more-events">
      <div class="col-6">
        <% @events.each do |event| %>
        <div class="box mb-2" style="width: 160%;">
          <span></span>
          <div class="content">
            <h5><img src="https://acegif.com/wp-content/uploads/2022/fzk5d/76-open-close-mouth.gif" width="20px" />
            <%= event.title %> </h5>
            <hr>
            <div id="show-more-text">
              <p> <%= event.desc %> </p>
            </div>
            <br>
            <div class="d-flex justify-content-between">
              <div class="col-8 fw-bold lh-lg" id="event-text">
                <%= event.venue  %> - <%= event.address %>
                <br>
                <%= event.date.strftime("%A, %d %b %Y at %l:%M %p GMT")  %>
              </div>
              <div class="p-1">
                <div>
                  <%= link_to "RSVP", event_attendees_path(event), data: { turbo_method: :post }, remote: true, class:"btn btn-secondary1 w-100 fw-bold text-light;" %>
                </div>
                <p class="pt-2"><%= pluralize(event.attendees.count, "attendee") %></p>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
    <div class="container flex-row">
      <div class="module-border-wrap">
        <div class="rounded w-100" style="height: 650px; position: sticky; top: 0;"
          data-controller="map"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<%= render "shared/navbar" %>

<div class="bg-main main-paddin min-vh-100" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://t4.ftcdn.net/jpg/04/09/70/87/360_F_409708782_HxuxOH8f7xSmj5p4ygbAbuJE74vGGj2N.jpg);">
  <div class="container" data-controller="coin-sound">
    <div class="detail-card">
      <div class="box box-show" id="box-application">
        <span></span>
        <div class="box-detail">
          <h1 class="text-center pb-4"> <strong> POST A NEW GAMING EVENT <br /></strong></h1>
              <h5><%= simple_form_for [@event] do |event| %>
                <%= event.input :title %>
                <%= event.input :date, as: :datetime, html5: true %>
                <%= event.input :venue %>
                <%= event.input :address %>
                <%= event.input :desc %>
                <%= event.input :photo, as: :file %>
                <%= event.submit "Submit", class: "btn col-3 btn-secondary1 mt-3 fw-bold text-light" %>
              <% end %>
          <%= link_to "Events", events_path, class: "btn col-3 mt-3 btn-secondary2 fw-bold text-light" %>
        </div>
      </div>
    </div>
  </div>
</div>