config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root to: "pages#home"

  resources :jobs do
    resources :applications, only: [:new, :create, :show, :index]
  end
  resources :events, only: [:index, :new, :create, :show, :destroy] do
    resources :attendees, only: [:index, :create, :new]
  end

  resources :applications, only: [:destroy]
  resources :pages, only: [:index, :show]

  post "/levelup", to: "pages#levelup"
end

app/views/pages/home.html.erb
<link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
<script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>

<!-- First Parallax Section -->
<%= render "shared/main-navbar" %>
<div class="paral paralsec">
  <div class="banner-home">
    <div class="container nav-margin">
      <div>
        <h1 class="text-center mb-4 fronttext"><span data-controller="typed-js"></span></h1>
      </div>
      <div class="container">
        <%= form_tag jobs_path, method: :get do %>
        <div class="search">
          <div class="row">
            <div class="col-md-6">
              <div class="search-1">
                <i class='bx bx-search-alt'></i>
                  <%= text_field_tag :title, params[:title], placeholder: "Sound Designer"%>
              </div>
            </div>
            <div class="col-md-6">
              <div>
                <div class="search-2">
                  <i class='bx bxs-map' ></i>
                    <%= text_field_tag :city, params[:city], placeholder: "Berlin, Germany"%>
                  <button>Find Job</button>
                </div>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!-- Second Parallax Section -->
<div class="paral paralsec1" style="min-height: 120vh;">
  <div class="container">
    <div class="row justify-content-evenly top-pad">
      <div class="card purple card-length d-flex flex-row" data-aos="zoom-out-right">
        <div>
          <img src="https://i.gifer.com/origin/69/6966a9ad90c9cfc1e1a8330086f61536_w200.gif" width="100px" />
        </div>
        <div>
          <h4 style="margin-left: 20px;"> The Gaming Industry is now bigger than the movie and music industry ... combined! </h4>
        </div>
      </div>
      <div class="col-4"></div>
    </div>
    <div class="row justify-content-evenly my-5">
      <div class="col-4"></div>
      <div class="card green card-length d-flex flex-row" data-aos="zoom-out-left">
       <img src="https://i.gifer.com/origin/d4/d459d3d5a51f7c5224f71daa9f54318a.gif" width="70px" />
        <h4 style="margin-left: 20px;"> There are more than 2.7 billion gamers worldwide today. </h4>
      </div>
    </div>
    <div class="row justify-content-evenly my-5">
      <div class="card purple card-length d-flex flex-row" data-aos="zoom-out-right">
      <img src="https://64.media.tumblr.com/bdcd75a1aab889887222de90a1ed8246/tumblr_inline_ppm6bn5RHM1rtx1y2_1280.gif" width="130px" />
       <h4 style="margin-right: 20px;"> You don't have to be a coder to work in gaming! Musicians, artists, sales.. the gaming industry needs 'em all! </h4>
      </div>
      <div class="col-4"></div>
    </div>
    <div class="row justify-content-evenly bottom-pad">
      <div class="col-4"></div>
      <div class="card green card-length d-flex flex-row" data-aos="zoom-out-left">
        <img src="https://i.gifer.com/origin/83/83c09a2e9a4d7ca070a4640ff9c7125f_w200.gif" width="120px" />
        <h4> Use your skills, work in your passion, it's all possible! </h4>
      </div>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<%= render "shared/navbar" %>

<div class="bg-main min-vh-100" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://t4.ftcdn.net/jpg/04/09/70/87/360_F_409708782_HxuxOH8f7xSmj5p4ygbAbuJE74vGGj2N.jpg);">


  <div class="container d-flex flew-row top-pad">
    <div class="avatar-dash" data-controller="progress-bar" data-points="<%= @user.xp %>" data-level-up="<%= @user.levelUp %>" data-progress-bar-target="avatar">
      <%= image_tag current_user.image %>
      <div data-progress-bar-target="pyro">
        <div data-progress-bar-target="before"></div>
        <div data-progress-bar-target="after"></div>
      </div>
      <h1 class="text-center pt-5 pb-4">LEVEL <%= @user.level %></h1>
      <div class="exp">
        <span class="xp" data-progress-bar-target="xp"></span>
      </div>
      <div class="text-center green-text">
        <h4 class="py-4">Class: <%= @user._class %></h4>
        <% if @user.level >= 2 %>
          <p>--> Unlocked New Feature!! <--</p>
          <p>+1 Visibility into # of Applicants</p>
        <% end %>
      </div>
    </div>

    <div class="col-8">
      <h1 class="text-center mb-4"><%= @user.firstName %>'s Profile </h1>
      <div class="tabs justify-content-end pt-4" style="width: 110%;">
        <div class="tab-2">
          <label for="tab2-1">Profile</label>
          <input id="tab2-1" name="tabs-two" type="radio" checked="checked">
          <div class="tab-text">
            <div>
              <h3 class="text-center pb-3">Main Description</h3>
              <p class="text-center"><%= @user.desc %></p>
            </div>
            <div class="p-4">
              <h3 class="text-center pb-3">Skills</h3>
              <h4 class="text-center pb-3">Category: <%= @user.category%></h4>
              <ul class="pb-3 list-unstyled d-flex">
                <div class="text-center col-6">
                  <li><p><%= @user.skills[0]%></p></li>
                  <li><p><%= @user.skills[1]%></p></li>
                  <li><p><%= @user.skills[2]%></p></li>
                  <li><p><%= @user.skills[3]%></p></li>
                </div>

                <div class="text-center col-6">
                  <li><p><%= @user.skills[4]%></p></li>
                  <li><p><%= @user.skills[5]%></p></li>
                  <li><p><%= @user.skills[6]%></p></li>
                </div>

              </ul>
            </div>
          </div>
        </div>


        <div class="tab-2">
          <label for="tab2-2">Application</label>
          <input id="tab2-2" name="tabs-two" type="radio">
          <div class="tab-text">

          <h4 class="text-center mb-4">Application</h4>
            <div class="row justify-content-center" id="content-height">
              <% @applications.each do |application| %>
              <div class="box">
                <span></span>
                <div class="content d-flex">
                  <div class="col-4 pt-1">
                    <h6> Application #<%= application.id %></h6>
                    <%= cl_image_tag application.employer.image.key, class:"w-50" %>
                  </div>
                  <div class="col-8">
                    <h5> <%= application.job.title  %></h5>
                    <p> <%= application.job._type  %>: €<%=application.job.salary%>/year </p>
                    <p> You sent application on <%= application.created_at.strftime("%A, %d %b %Y at %l:%M %p GMT") %></p>
                    Status: In Progress. Employer Reviewing.
                    <% if @user.level >= 2 %>
                      <p># of applicants: <strong><%= Application.where(job_id: application.job.id).count %></strong></p>
                    <% end %>
                    <hr>
                    <p style="margin:0;"><%= link_to raw("<i class=\"fa-solid fa-trash-can\"></i>"), application_path(application), data: { turbo_method: :delete }, class:"trash-hover" %></p>
                  </div>
                </div>
              </div>
              <% end %>
            </div>
          </div>
        </div>

        <div class="tab-2">
          <label for="tab2-3">Event</label>
          <input id="tab2-3" name="tabs-two" type="radio">
          <div class="tab-text">
            <h4 class="text-center pb-4">Event</h4>
            <div class="row justify-content-center" id="content-height">
              <%# showing events  %>
              <% @events.each do |event_id| %>
              <% event = Event.find(event_id) %>
              <div class="box">
                <span></span>
                <div class="content d-flex">
                  <div class="col-3">
                    <h5>Event #<%= event.id %></h5>
                  </div>
                  <div class="col-9">
                    <h5> <%= event.title  %></h5>
                    <p> <%= event.venue  %>: <%=event.desc%> </p>
                    <p> The event is on <strong><%= event.date.strftime("%A, %d %b %Y at %l:%M %p GMT")  %></strong></p>
                    <p> Number of attendees: <%= event.attendees.count  %></p>
                  </div>
                </div>
              </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>